# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - AutoMods

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          
      - name: Replace database properties in application.properties
        run: |
          sed -i "s|spring.datasource.url=.*|spring.datasource.url=${{ env.DATABASE_URL }}|g" src/main/resources/application.properties
          sed -i "s|spring.datasource.username=.*|spring.datasource.username=${{ env.DATABASE_USERNAME }}|g" src/main/resources/application.properties
          sed -i "s|spring.datasource.password=.*|spring.datasource.password=${{ env.DATABASE_PASSWORD }}|g" src/main/resources/application.properties
          sed -i "s|spring.flyway.url=.*|spring.datasource.password=${{ env.DATABASE_URL }}|g" src/main/resources/application.properties
          sed -i "s|spring.flyway.user=.*|spring.datasource.password=${{ env.DATABASE_USERNAME }}|g" src/main/resources/application.properties
          sed -i "s|spring.flyway.password=.*|spring.datasource.password=${{ env.DATABASE_PASSWORD }}|g" src/main/resources/application.properties

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AutoMods'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6AB263A290F04E5EB1545D319C8603B5 }}
          package: '*.jar'
